dist: trusty
language: python
python:
  - "3.6"
install: |
  set -e
  set -o pipefail
  python -m pip install --upgrade pip
  pip install --progress-bar off -e .
  pip list
script: |
  set -e
  set -o pipefail
  #ci/run-tests.sh
  echo "Travis"
branches:
  only:
    # just exclude for now
    - master-old
    #- /^v\d+\.\d+(\.\d+)?(-rc\d+)?$/
