#!/bin/bash

"$@" &

START=$(date +%s)

# generic downloader
if [ "$#" -eq "5" ]; then
    printcmd=$(printf "   \033[0;37mDownloading LEGO train files from: %s \033[0m" $3)
# old downloader
else
    if [ -z "$11" ]; then
      if [ $9 -eq 1 ]; then
        printcmd=$(printf "   \033[0;37mDownloading LEGO train files from: %s/%s_child_%s/%s/%s.root\033[0m" $3 $8 $4 "$5" $6)
      else
        printcmd=$(printf "   \033[0;37mDownloading LEGO train files from: %s/%s/%s/%s.root\033[0m" $3 $8 "$5" $6)
      fi
    else
      if [ $9 -eq 1 ]; then
        printcmd=$(printf "   \033[0;37mDownloading LEGO train files from: %s/%s_child_%s/%s/%s/%s.root\033[0m" $3 $8 $4 ${11} "$5" $6)
      else
        printcmd=$(printf "   \033[0;37mDownloading LEGO train files from: %s/%s/%s/%s/%s.root\033[0m" $3 $8 ${11} "$5" $6)
      fi
    fi
fi

printf "$printcmd\n" > /dev/tty

printf "   Running downloader: " > /dev/tty
while kill -0 $!; do
  printf "." > /dev/tty
  sleep 2

  if [ "$(( $(date +%s) - $START ))" -gt "10" ]; then
    printf "\r                               " > /dev/tty
    printf "\r   Running downloader: " > /dev/tty
    START=$(date +%s)
  fi

done

printf "\r                      " > /dev/tty
printf "\r   Downloader finished\n\n" > /dev/tty
