
database: /home/bvolkel/HF/MachineLearningHEP/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_HM_V0.yml

data_or_mc: mc

analysis: V0vspt_perc_v0m

distribution: n_tracklets

x_range:
    - 100
    - 0
    - 100

out_file: n_tracklets_HM_Lc_mc.root
