
database: /home/bvolkel/HF/MachineLearningHEP/machine_learning_hep/data/data_prod_20200417/database_ml_parameters_D0pp_0417.yml

data_or_mc: mc

analysis: MBvspt_perc_v0m

distribution: n_tracklets

x_range:
    - 100
    - 0
    - 100

out_file: n_tracklets_MB_D0_mc.root
