
database: /home/bvolkel/HF/MachineLearningHEP/machine_learning_hep/data/data_prod_20200304/database_ml_parameters_LcpK0spp_0304_HMV0M.yml

data_or_mc: data

query_all: "is_ev_rej == 0"

analysis: V0vspt_perc_v0m

distribution: n_tracklets

x_range:
    - 101
    - -0.5
    - 100.5

slice_cuts:
    - "perc_v0m <= 0.1 and perc_v0m >= 0"

required_columns:
    - perc_v0m

period_cuts:
    - "run_number > 256941"
    - null
    - null

out_file: n_tracklets_HM_Lc_data.root
