from ROOT import TFile, TH1F, TCanvas, TF1
from ROOT import gROOT, gStyle, TLegend
gROOT.SetStyle("Plain")
gStyle.SetOptStat(0)
gStyle.SetOptStat(0000)
gStyle.SetPalette(0)
gStyle.SetCanvasColor(0)
gStyle.SetFrameFillColor(0)
gStyle.SetOptTitle(0)

filedatatrg = TFile.Open("/data/DerivedResults/D0kAnywithJets/vAN-20200304_ROOT6-1/pp_2018_data/376_20200304-2028/resultsSPDvspt_ntrkl/masshisto.root")
filedatamb = TFile.Open("/data/DerivedResults/D0kAnywithJets/vAN-20200304_ROOT6-1/pp_2018_data/376_20200304-2028/resultsMBvspt_ntrkl/masshisto.root")
hden = filedatamb.Get("hn_tracklets_corr")
hnum = filedatatrg.Get("hn_tracklets_corr")
hratio = hnum.Clone("hratio")
hdend = filedatamb.Get("hn_tracklets_corr_withd")
hnumd = filedatatrg.Get("hn_tracklets_corr_withd")
hratiod = hnumd.Clone("hratiod")
hratio.Divide(hden)
hratiod.Divide(hdend)

ctrigger = TCanvas('ctrigger', 'The Fit Canvas')
ctrigger.SetCanvasSize(2500, 2000)
ctrigger.Divide(2, 2)
ctrigger.cd(1)
leg = TLegend(.5, .65, .7, .85)
leg.SetBorderSize(0)
leg.SetFillColor(0)
leg.SetFillStyle(0)
leg.SetTextFont(42)
leg.SetTextSize(0.035)

hden.GetYaxis().SetTitle("Entries")
hden.GetXaxis().SetTitle("n_tracklets_corr")
hden.GetXaxis().SetRangeUser(0.,150.)
hden.Draw("pe");
hden.SetLineColor(2)
hnum.Draw("pesame")
leg.AddEntry(hden, "MB", "LEP")
leg.AddEntry(hnum, "SPD", "LEP")
leg.Draw()
ctrigger.cd(2)
hratio.GetYaxis().SetTitle("SPD/MB (no D required)")
hratio.GetXaxis().SetTitle("n_tracklets_corr")
hratio.GetXaxis().SetRangeUser(0.,150.)
hratio.Draw("pe");
func = TF1("func", "([0]/(1+TMath::Exp(-[1]*(x-[2]))))", 0, 140)
func.SetParameters(300, .1, 570)
func.SetParLimits(1, 0., 10.)
func.SetParLimits(2, 0., 1000.)
func.SetRange(40., 110.)
func.SetLineWidth(1)
hratio.Fit(func, "L", "", 40, 110)
func.Draw("same")
ctrigger.cd(3)
hnumd.GetYaxis().SetTitle("Entries")
hnumd.GetXaxis().SetTitle("n_tracklets_corr")
hnumd.GetXaxis().SetRangeUser(0.,150.)
hdend.SetLineColor(2)
hnumd.Draw("pe")
hdend.Draw("pesame");
leg.Draw()
ctrigger.cd(4)
hratiod.GetYaxis().SetTitle("SPD/MB (D required)")
hratiod.GetXaxis().SetTitle("n_tracklets_corr")
hratiod.GetXaxis().SetRangeUser(0.,150.)
hratiod.Draw("pe");
funcd = TF1("func", "([0]/(1+TMath::Exp(-[1]*(x-[2]))))", 0, 140)
funcd.SetParameters(300, .1, 570)
funcd.SetParLimits(1, 0., 10.)
funcd.SetParLimits(2, 0., 1000.)
funcd.SetRange(40., 110.)
funcd.SetLineWidth(1)
hratiod.Fit(funcd, "L", "", 40, 110)
func.SetLineColor(1)
func.Draw("same")
funcd.SetLineColor(4)
funcd.Draw("same")
ctrigger.SaveAs("SPDtrigger.pdf")
foutput = TFile.Open("triggercorrections/ftriggerSPD2018.root", "recreate")
foutput.cd()
hratio.Write()
func.Write()
