activate_models:
  BinaryClassification:
    keras:
      simple_one_layer_binary_class: false
      simple_two_layer_binary_class: true
    scikit:
      adaboost_classifier: true
      decision_tree_classifier: true
      random_forest_classifier: true
    xgboost:
      xgboost_classifier: true
  Regression:
    scikit:
      lasso: true
      linear_regression: true
      ridge: true
applytodatamc: true
binmax: 4
binmin: 2
case: Lc
doROC: true
doboundary: true
docorrelation: false
docrossvalidation: true
dogridsearch: false
doimportance: true
dolearningcurve: true
dopca: false
dopltregressionxy: false
dosignifopt: false
dostandard: false
dotesting: true
dotraining: true
loadsampleoption: true
mlsubtype: HFmeson
mltype: BinaryClassification
ncores: -1
nevt_bkg: 1000
nevt_sig: 1000
nkfolds: 5
rnd_shuffle: 12
rnd_splt: 12
test_frac: 0.2
