activate_models:
  BinaryClassification:
    keras:
      keras_simple_one_layer_binary_classifier: false
      keras_simple_two_layer_binary_classifier: true
    scikit:
      scikit_adaboost_classifier: true
      scikit_decision_tree_classifier: true
      scikit_random_forest_classifier: true
    xgboost:
      xgboost_classifier: true
  Regression:
    scikit:
      scikit_lasso_regression: true
      scikit_linear_regression: true
      scikit_ridge_regression: true
applytodatamc: true
binmax: 4
binmin: 2
case: Lc
doROC: true
doboundary: true
docorrelation: false
docrossvalidation: true
dogridsearch: false
doimportance: true
dolearningcurve: true
dopca: false
dopltregressionxy: false
dosignifopt: false
dostandard: false
dotesting: true
dotraining: true
loadsampleoption: true
mlsubtype: HFmeson
mltype: BinaryClassification
ncores: -1
nevt_bkg: 400000
nevt_sig: 400000
nkfolds: 5
rnd_shuffle: 12
rnd_splt: 12
test_frac: 0.2
