activate_models:
  BinaryClassification:
    keras:
      keras_simple_one_layer_binary_classifier: false
      keras_simple_two_layer_binary_classifier: false
    scikit:
      scikit_adaboost_classifier: false
      scikit_decision_tree_classifier: false
      scikit_random_forest_classifier: false
    xgboost:
      xgboost_classifier: true
  Regression:
    scikit:
      scikit_lasso_regression: false
      scikit_linear_regression: false
      scikit_ridge_regression: false
applytodatamc: false
binmax: 10000
binmin: 0
case: Dzero
doROC: false
doboundary: false
docorrelation: true
docrossvalidation: false
dogridsearch: false
doimportance: false
dolearningcurve: false
dopca: false
dopltregressionxy: false
dosignifopt: false
dostandard: false
dotesting: false
dotraining: false
loadsampleoption: true
mlsubtype: HFmeson
mltype: BinaryClassification
ncores: -1
nevt_bkg: 1000
nevt_sig: 1000
nkfolds: 5
rnd_shuffle: 12
rnd_splt: 12
test_frac: 0.2
