activate_keras: 1
activate_scikit: 1
activate_xgboost: 1
applytodatamc: 1
binmax: 8
binmin: 4
case: Lcnew
doROC: 1
doboundary: 1
docorrelation: 1
docrossvalidation: 1
dogridsearch: 1
doimportance: 1
dolearningcurve: 1
dopca: 0
dopltregressionxy: 1
dosignifopt: 1
dostandard: 0
dotesting: 1
dotraining: 1
loadsampleoption: 1
mlsubtype: HFmeson
mltype: BinaryClassification
ncores: -1
nevt_bkg: 200000
nevt_sig: 50000
nkfolds: 5
rnd_shuffle: 12
rnd_splt: 12
test_frac: 0.2
