#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_LcpK0spp_20200301.yml  -a MBvspt_perc_v0m
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml  -a MBvspt_perc_v0m
DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml  -a SPDvspt_ntrkl
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_D0pp_zg_0304.yml  -a MBvspt_ntrkl
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_LcpK0spp_20200301.yml  -a MBjetvspt
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_LcpK0spp_20200301.yml  -a MBvspt_ntrkl
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_LcpK0spp_20200301.yml  -a MBvspt_perc_v0m
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/data_prod_20200304/database_ml_parameters_Dspp.yml -a MBvspt_ntrkl
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/JetAnalysis/database_ml_parameters_LcpK0spp_test_0909.yml
#DISPLAY="" python do_entire_analysis.py -r submission/default_complete.yml -d data/JetAnalysis/database_ml_parameters_LcpK0spp_test_0201_D2H.yml
